repos:
  # 1️⃣  Code formatter (Black)
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        # Match Black’s default line length
        args: [--line-length=88]

  # 2️⃣  Import sorter (isort)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # 3️⃣  Linter (flake8)
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
